apiVersion: v1                                                                                            kind: Service
metadata:
  name: myredis-my-project
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.taretPort }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: my-project
    app.kubernetes.io/instance: myredisg
