version: "3"

services:
  PGSQL_DB:
    image: postgres:latest # Образ, который мы будем использовать
    container_name: PGSQL_DB # Имя, которым будет называться наш контейнер
    ports: # Порты, которые мы пробрасываем с нашего докер сервера внутрь контейнера
      - 5432:5432
    volumes: # Папка, которую мы пробросим с докер сервера внутрь контейнера
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment: # Переменные среды
      POSTGRES_PASSWORD: balashovdi12!3!! # Задаём пароль от пользователя postgres
      POSTGRES_DB: balashovdi-db # БД которая сразу же будет создана
      PGDATA: /var/lib/postgresql/data/pgdata # Путь внутри контейнера, где будет папка pgdata
    networks:
      balashovdi-my-netology-hw:
        ipv4_address: 172.22.0.10
    restart: always # Режим перезапуска контейнера. Контейнер всегда будет перезапускатьс
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: balashovdi@mymail.ru
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - 61231:80
    networks:
      balashovdi-my-netology-hw:
        ipv4_address: 172.22.0.20
    restart: always
  zabbix-server:
    image: zabbix/zabbix-server-pgsql
    links:
      - PGSQL_DB
    container_name: Zabbix-server
    environment:
      DB_SERVER_HOST: '172.22.0.10'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: balashovdi12!3!!
    ports:
      - 10051:10051
    networks:
      balashovdi-my-netology-hw:
        ipv4_address: 172.22.0.30
    restart: always
  zabbix_wgui:
    image: zabbix/zabbix-web-apache-pgsql
    links:
      - PGSQL_DB
      - zabbix-server
    container_name: balashovdi-netology-zabbix-frontend
    environment:
      DB_SERVER_HOST: '172.22.0.10'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: balashovdi12!3!!
      ZBX_SERVER_HOST: "zabbix_wgui"
      PHP_TZ: "Europe/Moscow"
    ports:
      - 80:8080
      - 443:8443
    networks:
      balashovdi-my-netology-hw:
        ipv4_address: 172.22.0.40
    restart: always



networks:
  balashovdi-my-netology-hw:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24
