PGSQL_DB:
  image: postgres:latest # Образ, который мы будем использовать
  container_name: PGSQL_DB # Имя, которым будет называться наш контейнер
  ports: # Порты, которые мы пробрасываем с нашего докер сервера внутрь контейнера
    - 5432:5432
  volumes: # Папка, которую мы пробросим с докер сервера внутрь контейнера
    - ./pg_data:/var/lib/postgresql/data/pgdata
  environment: # Переменные среды
    POSTGRES_PASSWORD: balashovdi12!3!! # Задаём пароль от пользователя postgres
    POSTGRES_DB: balashovdi-db # БД которая сразу же будет создана
    PGDATA: /var/lib/postgresql/data/pgdata # Путь внутри контейнера, где будет папка pgdata
  networks:
    balashovdi-my-netology-hw:
      ipv4_address: 172.22.0.10
  restart: always # Режим перезапуска контейнера. Контейнер всегда будет перезапускатьс
